---

- name: Reset the demo system
  collections:
    - community.libvirt
  hosts: libvirt
  gather_facts: no
  remote_user: truch
  become: true
  become_method: sudo
  vars:
    domain: template-host
    snapshot_name: ready_for_demo

  tasks:
  - name: Ensure the host is shutdown
    virt:
      name: '{{ domain }}'
      state: shutdown
    register: shutdown_vms

  - name: print out the VMs
    ansible.builtin.debug:
      msg: shutdown_vms

  - name: Revert to snapshot of the host
    ansible.builtin.command:
      'virsh snapshot-revert --domain "{{ domain }}" --snapshotname "{{snapshot_name }}"'
