---

- name: Patch Template Host
  hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  remote_user: ansible

  tasks:
  - name: Upgrade OS to latest packages available
    dnf:
      name: 'rsyslog'
      security: yes
      nobest: yes
      skip_broken: yes
      allowerasing: yes
      disable_gpg_check: yes
      state: latest
    register: updates

  - name: output updates dictionary
    debug:
      msg: "{{ updates.results }}"

  - name: Reboot server
    reboot:
    register: reboot_result
