---

- name: Get domains from libvirt
  collections:
    - community.libvirt
  hosts: all
  gather_facts: no
  become: true
  become_method: sudo
  remote_user: ansible

  vars:
    template_host: template-host
  tasks:
  - name: Start the template host
    community.libvirt.virt:
      name: '{{ template_host }}'
      state: running
