---

- name: Get domains from libvirt
  collections:
    - community.libvirt
  hosts: libvirt
  gather_facts: no
  remote_user: truch
  become: true
  become_method: sudo
  vars:
    template_host: template-host
  tasks:
  - name: Start the template host
    community.libvirt.virt:
      name: '{{ template_host }}'
      state: running


- name: Check that Template host is up
  hosts: templates
  gather_facts: no
  remote_user: ansible
  tasks:
  - name: Wait for connection...
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300
